### ISSUE TITLE
Drupal 7 Backport?

### ISSUE THREAD

**Issue by mr6volt** [Angerslave/drupal-youtrack#1]
Do you plan to backport this to work in Drupal 7? The current version doesn't appear to connect to YT 6.5

**Comment by sergsu** [comment]
I don't plan to backport it to D7 as I don't use it on D7. It makes sense to ask Jürgen, probably they have fixed it internally and just haven't released it yet.

**Comment by mr6volt** [comment]
So, i ended up fixing the module myself.

I attached the patch file to the Drupal.org issue... hopefully it gets noticed and added to the official release.

https://www.drupal.org/node/2719793#comment-11164809

**Comment by sergsu** [comment]
mr6volt thanks for the contribution to the module, I hope Jürgen will get some spare time soon to review it. I'm closing the issue here, let's discuss the D7 bug on drupal.org.

**Comment by mr6volt** [comment]
Sounds good!
